# This is a basic workflow to help you get started with Actions

name: main

# Controls when the workflow will run
on:
    schedule:
    workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: 'checkout codes'
        uses: actions/checkout@v1

      # Runs a single command using the runners shell
      - name: 'envirmentbuild'
        run: 
          pip install requests
      # Runs a set of commands ing the runners shell
      - name: environment variable and run
        run:
            python3 test.py
